### ISSUE TITLE
Sliding drawer

### ISSUE THREAD

**Issue by rangitha** [lukebrandonfarrell/react-native-navigation-drawer-extension#13]
This must be a really stupid question seeing that you use showOverlay under the hood - but would it be possible for me to hack a solution using your library where I could implement a drawer that slides in from left (and pushes the main content to the right)?

**Comment by lukebrandonfarrell** [comment]
Probably not. I'm rewriting the animations of this library next week to use translations for better performance on Android. I'll have a quick look into it. Interesting proposition.

**Comment by rangitha** [comment]
Great! I'll have an eye out on the releases
