### ISSUE TITLE
Blank background when opening drawer

### ISSUE THREAD

**Issue by devsoonote** [lukebrandonfarrell/react-native-navigation-drawer-extension#14]
When I put sideMenu on Main Screen, Main Screen is disappeared 
How Can I Fix? 
![image](https://user-images.githubusercontent.com/45555359/70517322-c946a900-1b7b-11ea-9ab4-74b299c94d52.png)

Help Me

**Comment by lukebrandonfarrell** [comment]
@devsoonote 

Are you using the built-in `RNNDrawer.showDrawer(...` function to open the 'drawer' ?

Also, could you share your code / project.

**Comment by devsoonote** [comment]
![image](https://user-images.githubusercontent.com/45555359/70580951-db1a6180-1bf8-11ea-9694-6fd845d81559.png)
![image](https://user-images.githubusercontent.com/45555359/70580968-ea99aa80-1bf8-11ea-9606-1b63eac2ffb9.png)

**Comment by lukebrandonfarrell** [comment]
@devsoonote The drawer code looks fine. I think it is the `setRoot` which is causing this. A few things:

1. Where and when is the `setRoot` code being called ?
2. Is the screen behind only disappearing when the drawer is opened ?
3. Does your `setRoot` work without the drawer?

**Comment by devsoonote** [comment]
setRoot is working. 
just When the drawer is opened, disappearing
![image](https://user-images.githubusercontent.com/45555359/70602944-e2f9f600-1c38-11ea-90f4-ff9228dee4a8.png)

And setRoot is index.js

**Comment by WASHSWATDAVID** [comment]
The problem was layout's background color. because of overlay size charged fully so it must changed layout color to transparent.

```
RNNDrawer.showDrawer({
    component: {
      name: "SideMenuScreen",
      passProps: {
        animationOpenTime: 400,
        animationCloseTime: 400,
        direction: "left",
        dismissWhenTouchOutside: true,
        fadeOpacity: 0.6,
        drawerScreenWidth: 302,
        drawerScreenHeight: "100%",
        parentComponentId: componentId,
      },
      options: {
        layout: {
          backgroundColor: 'transparent', // this is important
        }
      }
    }
  });
```

**Comment by lukebrandonfarrell** [comment]
@WASHSWATDAVID That is interesting, not sure if this is worth noting in the docs, I've never encountered it... do you have a link to a project which we can download and reproduce this?

@devsoonote Does the solution provided by @WASHSWATDAVID work for you?

**Comment by WASHSWATDAVID** [comment]
Yeap. she might working also cause she's my team🤣🤣🤣 
I think it's very strange situations. I'm not sure about previous(maybe higher?) versions but at least its' not working on 2.27.8.

I got the testing that launched just overlay but It also had a some blank screen when drawer opened. I thinks it's better to this library add that options or update documentation.
anyway rnn document is suck and thanks for your working!

**Comment by devsoonote** [comment]
@lukebrandonfarrell  I got it. Thanks. David is my boss haha😅

**Comment by lukebrandonfarrell** [comment]
David is the boss 😎
