### ISSUE TITLE
SideMenuView swipe to open not working on android

### ISSUE THREAD

**Issue by DavidStummer** [lukebrandonfarrell/react-native-navigation-drawer-extension#17]
Tried in simulator and device. Works on iOS.

**Comment by lukebrandonfarrell** [comment]
@DavidStummer Thanks for the issue. This is not something I am able to work on at the minute unless you dig into the code and provide more info on the cause of the issue.

**Comment by DavidStummer** [comment]
It is fixed when I put a high zindex on the view with the pan responder.
I'll try to put a pr for it tomorrow

**Comment by Cheaterflums** [comment]
thanks David for pointing this out, I created a pull request for it, see #18

**Comment by lukebrandonfarrell** [comment]
@Cheaterflums Thanks for the PR
