### ISSUE TITLE
Getting a white screen when drawing menu

### ISSUE THREAD

**Issue by IamNotHuman** [lukebrandonfarrell/react-native-navigation-drawer-extension#19]
I'm using react-native-navigation@6.3.0 & react-native-navigation-drawer-extension@2.0.3 the functionality works fine but I get a white screen flash and then the drawer opens with the white screen in the background
<img width="396" alt="Captura de Pantalla 2020-03-29 a la(s) 12 05 12" src="https://user-images.githubusercontent.com/27880211/77856629-ae915200-71b5-11ea-8270-2e9b7d9a89f8.png">
 (Doesn't look good for the user)

**Comment by lukebrandonfarrell** [comment]
@IamNotHuman Thanks for flagging the issue. We are upgrading our client apps to RN 0.60 and RNN > 2.0.0 in the next two weeks. So if we come across this, it will sure be fixed.

**Comment by lukebrandonfarrell** [comment]
@Eduardoleor Thanks for the solution :) 

Would you mind explaining further what is `componentBackgroundColor`? Is the is a new property in later version of React Native Navigation. 

If this is the case universally, then we can patch the library to account for this.

**Comment by lukebrandonfarrell** [comment]
@Eduardoleor @IamNotHuman I have reproduced this while upgrading one of our projects... will fix it soon in next release.

**Comment by lukebrandonfarrell** [comment]
@IamNotHuman @Eduardoleor Fixed in version 3.x.x
