### ISSUE TITLE
How to Navigation.push from drawer

### ISSUE THREAD

**Issue by anglol** [lukebrandonfarrell/react-native-navigation-drawer-extension#2]
Hi,

I'm using your extension to handle my drawer. It works pretty well, but I have a problem when i want to push to another view from the drawer screen :

```javascript
Navigation.push(this.props.componentId, {
  component: {
    name: 'example.PushedScreen',
  }
});
```

Any idea ?

Thanks !

**Comment by anglol** [comment]
I found a solution. Have to pass the current componentId to the drawer (props) when I open it.

There is no bug, but I think you can add it to the documentation for others !

Thanks for this extension, it rocks :)

**Comment by lukebrandonfarrell** [comment]
@anglol Thanks :) Glad you solved it. The extension uses `showOverlay` under the hood, so anything you can do with overlays can be done with this.

**Comment by levannga1125** [comment]
@lukebrandonfarrell i'm using SideMenuView and i have the same problem with @anglol , please give me suggestion

**Comment by lukebrandonfarrell** [comment]
@levannga1125 You need to send the ID of the screen which opened the drawer to the drawer with `passProps` you could call it `parentComponentId` and then do `Navigation.push(parentComponentId`

**Comment by levannga1125** [comment]
@lukebrandonfarrell Thanks so much, it's work.
