### ISSUE TITLE
"useNativeDriver" is required on animation of drawer as of RN 0.62

### ISSUE THREAD

**Issue by TylerNRobertson** [lukebrandonfarrell/react-native-navigation-drawer-extension#20]
When openning & closing the drawer the React Native Animated API requires "useNativeDriver" as a required prop of true or false. Weird how they cant just default it to false on their end but its throwing a warning in the library.

Nothing breaks just a the warning that would be nice to get muted :)

**Comment by lukebrandonfarrell** [comment]
@TylerNRobertson I'm not 100% on what the issue is

To give some background, this library uses the native drivers for animation as it is much faster. That means we animate with `transforms` instead of margins.

**Comment by lukebrandonfarrell** [comment]
@TylerNRobertson I have reproduced this while upgrading one of our projects... will fix it soon in next release.
