### ISSUE TITLE
Add Swipe to open Drawer

### ISSUE THREAD

**Issue by cinder92** [lukebrandonfarrell/react-native-navigation-drawer-extension#3]
Hello, thanks for this cool extension, at this time it could be amazing if you can add a swipe gesture in order to open or close the drawer

**Comment by lukebrandonfarrell** [comment]
@cinder92 Thanks.

I've been thinking about what the API would look like for achieving this, and happy to contribute this week to build this feature.

My initial idea for opening the drawer with a swipe was to include a component in the library called `<DrawerView />`. This will be a ordinary view wrapped with a PanResponder which you can wrap your components with, it will allow you to swipe the side of the screen to trigger a callback function.

The probs of the `<DrawerView />` may look something like this `<DrawerView left={ // Callback function to open drawer } />` where you'd have `left`, `right`, `top` and `bottom` as callbacks on this component for detecting swiping.

Do you have any ideas for how'd you'd like the API to look, to give me some insight of you are going to be using it?

**Comment by ajmalsalim** [comment]
@lukebrandonfarrell Keen on this. One use case can be using the drawer as a BottomSheet.

**Comment by lukebrandonfarrell** [comment]
@ajmalsalim for sure. 

The implementation is going to be a little harder than I first anticipated because we need to open the drawer using a RNN action BUT we want to open it at position 0 and allow the users finger to control the animation based on position, that's not a problem... still thinking about a way to do this without making the API too clunky.

**Comment by lukebrandonfarrell** [comment]
@ajmalsalim @cinder92 

Made a new branch called `feature_swipe_open` which partially adds this functionality, and can be used as such:

```
import { SideMenuView } from "react-native-navigation-drawer-extension";

 <SideMenuView
        style={{ flex: 1 }}
        left={() => Navigation.showDrawer(
          component("BrandsSideMenu", {
            parentId: this.props.componentId
          })
        )}>
```

Still a few fixes to do with using this in a `ScrollView` before it gets merged into master and not sure if I'm entirely happy with the API yet, be sure to check it out though, and let me know what you guys think.

**Comment by lukebrandonfarrell** [comment]
@ajmalsalim @cinder92 

Still cleaning this up but looks good so far 🎉

![slide](https://user-images.githubusercontent.com/18139277/55156962-2536e200-5153-11e9-8fe2-e7aba00e5c10.gif)

**Comment by ajmalsalim** [comment]
@lukebrandonfarrell looks promising.
