### ISSUE TITLE
Invariant Violation: Could not find "store" in either the context or props of "Connect(DrawerScreen)"

### ISSUE THREAD

**Issue by ajmalsalim** [lukebrandonfarrell/react-native-navigation-drawer-extension#4]
Was trying to use DrawerScreen with Redux but getting this error message

![Screenshot 2019-03-28 at 3 10 33 PM](https://user-images.githubusercontent.com/2766056/55129620-db0e2a80-516b-11e9-8b9b-824b5f9acb5a.jpg)

`Navigation.registerComponent(DRAWER_SCREEN, () => WrappedComponent(DrawerScreen));` is working fine but 
`Navigation.registerComponent(DRAWER_SCREEN, () => RNNDrawer(DrawerScreen));` is not. Am I missing something?

**Comment by lukebrandonfarrell** [comment]
What about using `Navigation.registerComponentWithRedux`?

**Comment by ajmalsalim** [comment]
@lukebrandonfarrell Thanks but seems it is not helping.

**Comment by lukebrandonfarrell** [comment]
@ajmalsalim 

Could you share with me your files in which:

1. You register your drawer component `Navigation.registerComponent(...`
2. Your side menu component (The one you wrap with `RNNDrawer `)

And I can see if I can help you

**Comment by ajmalsalim** [comment]
Hi @lukebrandonfarrell,

It was a stupid mistake. Forgot to wrap my component using `<Provider>`.

Thanks for offering help!

**Comment by lukebrandonfarrell** [comment]
Alright no problem, glad you solved it! 😂😂
