### ISSUE TITLE
this.unsubscribeSwipeStart is not a function....

### ISSUE THREAD

**Issue by juddey** [lukebrandonfarrell/react-native-navigation-drawer-extension#8]
I'm using this component in my project, thank you.

I've seen quite a few of the `this.unsubscribeSwipeStart is not a function....` red screens come up while I'm developing my app but they've always been after some sort of app crash so never paid much attention, thinking they were just fallout.

I think I've got a solid repro case tho. Heres a video:
![out](https://user-images.githubusercontent.com/7445602/60774852-83ba2600-a16e-11e9-88de-063d8c2064b6.gif)

At the end of the vid you'll see the burger menu being tapped. This is supposed to flick the drawer open so the user can select a logout option, which clearly doesn't happen.

Then, I touch anywhere on the emulator and I get the ol':
![image](https://user-images.githubusercontent.com/7445602/60774859-96ccf600-a16e-11e9-928c-caca863c6539.png)

This is happening in debug mode on Android 6.0. I'll be able to tell you shortly if this happens in release mode.

Any suggestions as to what might be causing this?

**Comment by juddey** [comment]
Confirming the same behaviour on release build - (no red debugger screen to show)

**Comment by lukebrandonfarrell** [comment]
@juddey Thanks for the comprehensive bug report. I'll be sure to look into it in the next few days and update the library with a fix.

**Comment by juddey** [comment]
Thanks Luke. If theres anything you need from my side, let me know.

**Comment by lukebrandonfarrell** [comment]
@juddey this has now been fixed in 2.0.0, although check the documentation as this is a breaking change as the method calls have changed to avoid monkey patching RNN.

**Comment by juddey** [comment]
@lukebrandonfarrell Awesome! I'll give it a try. Thank you very much. :raised_hands:
